FROM php:8.2-fpm

# Устанавливаем зависимости
RUN apt-get update && apt-get install -y \
    git unzip libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql

# Устанавливаем composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www